package output

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os/exec"
	"strings"

	"github.com/anurag/tracescope/internal/analyzer"
	"github.com/anurag/tracescope/internal/ownership"
)

const commentMarker = "<!-- tracescope-blast-radius -->"

// FormatMarkdownComment builds a Markdown blast radius report.
func FormatMarkdownComment(result *analyzer.AnalysisResult) string {
	var b strings.Builder

	b.WriteString(commentMarker + "\n")
	b.WriteString("## TraceScope — Blast Radius\n\n")

	high, medium, low := groupByRiskMD(result.AffectedFunctions)

	// Summary table
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Changed files | %d |\n", len(result.ChangedFiles)))
	b.WriteString(fmt.Sprintf("| Changed functions | %d |\n", len(result.ChangedFunctions)))
	total := len(result.AffectedFunctions)
	if result.TotalAffected > total {
		total = result.TotalAffected
	}
	b.WriteString(fmt.Sprintf("| Affected functions | %d |\n", total))
	b.WriteString(fmt.Sprintf("| Risk | %d high, %d medium, %d low |\n", len(high), len(medium), len(low)))
	b.WriteString(fmt.Sprintf("| Max depth | %d |\n\n", result.MaxDepth))

	// Risk sections
	if len(high) > 0 {
		b.WriteString("### :red_circle: High Risk\n\n")
		writeAffectedMD(&b, high)
	}
	if len(medium) > 0 {
		b.WriteString("### :yellow_circle: Medium Risk\n\n")
		writeAffectedMD(&b, medium)
	}
	if len(low) > 0 {
		b.WriteString("<details>\n<summary>:green_circle: Low Risk (" + fmt.Sprintf("%d", len(low)) + ")</summary>\n\n")
		writeAffectedMD(&b, low)
		b.WriteString("</details>\n\n")
	}

	if len(result.AffectedFunctions) == 0 {
		b.WriteString("No affected functions found in blast radius. :white_check_mark:\n\n")
	}

	if result.TopN > 0 && result.TotalAffected > result.TopN {
		b.WriteString(fmt.Sprintf("*Showing top %d of %d affected functions.*\n\n", result.TopN, result.TotalAffected))
	}

	// Reviewers section
	if result.Ownership != nil {
		if oi, ok := result.Ownership.(*ownership.OwnershipInfo); ok && len(oi.SuggestedReviewers) > 0 {
			b.WriteString("### Suggested Reviewers\n\n")
			b.WriteString("| Reviewer | Files |\n")
			b.WriteString("|----------|-------|\n")
			for _, r := range oi.SuggestedReviewers {
				b.WriteString(fmt.Sprintf("| %s | %d |\n", r.Owner, r.FileCount))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n*Generated by [TraceScope](https://github.com/anurag/tracescope)*\n")

	return b.String()
}

func writeAffectedMD(b *strings.Builder, funcs []analyzer.AffectedFunction) {
	b.WriteString("| Function | File | Callers | Depth |\n")
	b.WriteString("|----------|------|---------|-------|\n")
	for _, f := range funcs {
		b.WriteString(fmt.Sprintf("| `%s` | `%s:%d` | %d | %d |\n",
			f.Node.Name, f.Node.FilePath, f.Node.StartLine, f.CallerCount, f.Depth))
	}
	b.WriteString("\n")
}

func groupByRiskMD(funcs []analyzer.AffectedFunction) (high, medium, low []analyzer.AffectedFunction) {
	for _, f := range funcs {
		switch f.Risk {
		case analyzer.RiskHigh:
			high = append(high, f)
		case analyzer.RiskMedium:
			medium = append(medium, f)
		case analyzer.RiskLow:
			low = append(low, f)
		}
	}
	return
}

// PostGitHubComment posts or updates a blast radius comment on the current PR.
func PostGitHubComment(result *analyzer.AnalysisResult) error {
	// Check gh is available
	if _, err := exec.LookPath("gh"); err != nil {
		return fmt.Errorf("'gh' CLI not found — install from https://cli.github.com")
	}

	// Get current PR number
	prNum, err := getCurrentPR()
	if err != nil {
		return fmt.Errorf("detecting current PR: %w (are you on a PR branch?)", err)
	}

	body := FormatMarkdownComment(result)

	// Try to find and update existing comment
	existingID, err := findExistingComment(prNum)
	if err == nil && existingID != "" {
		return updateComment(existingID, body)
	}

	// Create new comment
	return createComment(prNum, body)
}

func getCurrentPR() (string, error) {
	out, err := exec.Command("gh", "pr", "view", "--json", "number", "-q", ".number").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func findExistingComment(prNum string) (string, error) {
	out, err := exec.Command("gh", "api",
		fmt.Sprintf("repos/{owner}/{repo}/issues/%s/comments", prNum),
		"--jq", fmt.Sprintf(`.[] | select(.body | contains("%s")) | .id`, commentMarker),
	).Output()
	if err != nil {
		return "", err
	}
	id := strings.TrimSpace(string(out))
	if id == "" {
		return "", fmt.Errorf("not found")
	}
	// If multiple lines, take the first
	if idx := strings.Index(id, "\n"); idx != -1 {
		id = id[:idx]
	}
	return id, nil
}

func updateComment(commentID, body string) error {
	payload, err := json.Marshal(map[string]string{"body": body})
	if err != nil {
		return fmt.Errorf("marshaling payload: %w", err)
	}
	cmd := exec.Command("gh", "api", "-X", "PATCH",
		fmt.Sprintf("repos/{owner}/{repo}/issues/comments/%s", commentID),
		"--input", "-")
	cmd.Stdin = bytes.NewReader(payload)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("updating comment: %s", string(out))
	}
	return nil
}

func createComment(prNum, body string) error {
	cmd := exec.Command("gh", "pr", "comment", prNum, "--body", body)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("creating comment: %s", string(out))
	}
	return nil
}
