package output

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/anurag/tracescope/internal/analyzer"
	"github.com/anurag/tracescope/internal/graph"
	"github.com/anurag/tracescope/internal/ownership"
)

const commentMarker = "<!-- tracescope-blast-radius -->"

// repoRelativePath renders a graph file path for a PR comment.
//
// Graph nodes store absolute paths from whichever machine ran `tracescope
// index`, so printing them raw publishes that machine's directory layout into
// a comment anyone can read. Render them relative to the working directory —
// in CI that is the repository root — so a row reads
// internal/analyzer/blast_radius.go:95 rather than C:\Users\...\internal\...
//
// A path that is not under the base keeps its absolute form: a truthful
// absolute path beats a fragment that looks repo-relative but is not. It is
// still slash-normalised, so Windows separators never reach the comment.
func repoRelativePath(p, base string) string {
	if p == "" || base == "" || !filepath.IsAbs(p) {
		return filepath.ToSlash(p)
	}
	rel, err := filepath.Rel(base, p)
	if err != nil || rel == ".." || strings.HasPrefix(rel, ".."+string(filepath.Separator)) {
		return filepath.ToSlash(p)
	}
	return filepath.ToSlash(rel)
}

// FormatMarkdownComment builds a Markdown blast radius report.
func FormatMarkdownComment(result *analyzer.AnalysisResult) string {
	var b strings.Builder
	base, _ := os.Getwd()

	b.WriteString(commentMarker + "\n")
	b.WriteString("## TraceScope — Blast Radius\n\n")

	high, medium, low := groupByRiskMD(result.AffectedFunctions)

	// Summary table
	b.WriteString("| Metric | Value |\n")
	b.WriteString("|--------|-------|\n")
	b.WriteString(fmt.Sprintf("| Changed files | %d |\n", len(result.ChangedFiles)))
	b.WriteString(fmt.Sprintf("| Changed functions | %d |\n", len(result.ChangedFunctions)))
	total := len(result.AffectedFunctions)
	if result.TotalAffected > total {
		total = result.TotalAffected
	}
	b.WriteString(fmt.Sprintf("| Affected functions | %d |\n", total))
	b.WriteString(fmt.Sprintf("| Risk | %d high, %d medium, %d low |\n", len(high), len(medium), len(low)))
	b.WriteString(fmt.Sprintf("| Resolution confidence | %d exact, %d heuristic, %d ambiguous skipped, %d unresolved |\n",
		result.ResolutionStats.ExactCallEdges,
		result.ResolutionStats.HeuristicCallEdges,
		result.ResolutionStats.AmbiguousCalls,
		result.ResolutionStats.UnresolvedCalls,
	))
	b.WriteString(fmt.Sprintf("| Max depth | %d |\n\n", result.MaxDepth))

	if len(result.AffectedFunctions) > 0 {
		b.WriteString("### Reviewer Focus\n\n")
		b.WriteString("Prioritize high-score public/runtime paths first; manually inspect heuristic or ambiguous paths before merging.\n\n")
		writeTopRisksMD(&b, result.AffectedFunctions, 5, base)
	}

	if len(result.ResolutionIssues) > 0 {
		b.WriteString("### Resolution Diagnostics\n\n")
		writeResolutionIssuesMD(&b, result.ResolutionIssues, 10, base)
	}

	// Risk sections
	if len(high) > 0 {
		b.WriteString("### :red_circle: High Risk\n\n")
		writeAffectedMD(&b, high, base)
	}
	if len(medium) > 0 {
		b.WriteString("### :yellow_circle: Medium Risk\n\n")
		writeAffectedMD(&b, medium, base)
	}
	if len(low) > 0 {
		b.WriteString("<details>\n<summary>:green_circle: Low Risk (" + fmt.Sprintf("%d", len(low)) + ")</summary>\n\n")
		writeAffectedMD(&b, low, base)
		b.WriteString("</details>\n\n")
	}

	if len(result.AffectedFunctions) == 0 {
		b.WriteString("No affected functions found in blast radius. :white_check_mark:\n\n")
	}

	if result.TopN > 0 && result.TotalAffected > result.TopN {
		b.WriteString(fmt.Sprintf("*Showing top %d of %d affected functions.*\n\n", result.TopN, result.TotalAffected))
	}

	// Reviewers section
	if result.Ownership != nil {
		if oi, ok := result.Ownership.(*ownership.OwnershipInfo); ok && len(oi.SuggestedReviewers) > 0 {
			b.WriteString("### Suggested Reviewers\n\n")
			b.WriteString("| Reviewer | Files |\n")
			b.WriteString("|----------|-------|\n")
			for _, r := range oi.SuggestedReviewers {
				b.WriteString(fmt.Sprintf("| %s | %d |\n", r.Owner, r.FileCount))
			}
			b.WriteString("\n")
		}
	}

	b.WriteString("---\n*Generated by [TraceScope](https://github.com/anurag/tracescope)*\n")

	return b.String()
}

func writeAffectedMD(b *strings.Builder, funcs []analyzer.AffectedFunction, base string) {
	b.WriteString("| Function | File | Score | Callers | Depth | Confidence | Why path |\n")
	b.WriteString("|----------|------|-------|---------|-------|------------|----------|\n")
	for _, f := range funcs {
		if f.Node == nil {
			continue
		}
		b.WriteString(fmt.Sprintf("| `%s` | `%s:%d` | %d | %d | %d | %s | %s |\n",
			f.Node.Name,
			repoRelativePath(f.Node.FilePath, base),
			f.Node.StartLine,
			f.ReviewScore,
			f.CallerCount,
			f.Depth,
			formatConfidence(f.Confidence),
			formatImpactPathMD(f),
		))
	}
	b.WriteString("\n")
}

func writeTopRisksMD(b *strings.Builder, funcs []analyzer.AffectedFunction, limit int, base string) {
	if limit > len(funcs) {
		limit = len(funcs)
	}
	b.WriteString("| Score | Risk | Function | File | Owner | Confidence | Why | Impact path | Inspect first |\n")
	b.WriteString("|-------|------|----------|------|-------|------------|-----|-------------|---------------|\n")
	for i := 0; i < limit; i++ {
		f := funcs[i]
		if f.Node == nil {
			continue
		}
		b.WriteString(fmt.Sprintf("| %d | %s | `%s` | `%s:%d` | %s | %s | %s | %s | %s |\n",
			f.ReviewScore,
			f.Risk,
			f.Node.Name,
			repoRelativePath(f.Node.FilePath, base),
			f.Node.StartLine,
			formatOwnerMD(f.LastAuthor),
			formatConfidence(f.Confidence),
			f.Reason,
			formatImpactPathMD(f),
			formatInspectHintMD(f),
		))
	}
	b.WriteString("\n")
}

func writeResolutionIssuesMD(b *strings.Builder, issues []graph.ResolutionIssue, limit int, base string) {
	if limit > len(issues) {
		limit = len(issues)
	}
	b.WriteString("| Status | Kind | Location | Symbol | Receiver | Detail |\n")
	b.WriteString("|--------|------|----------|--------|----------|--------|\n")
	for i := 0; i < limit; i++ {
		issue := issues[i]
		location := repoRelativePath(issue.FilePath, base)
		if issue.Line > 0 {
			location = fmt.Sprintf("%s:%d", repoRelativePath(issue.FilePath, base), issue.Line)
		}
		if location == "" {
			location = "-"
		}
		symbol := issue.Symbol
		if symbol == "" {
			symbol = "-"
		}
		receiver := issue.Receiver
		if receiver == "" {
			receiver = "-"
		}
		detail := issue.Detail
		if detail == "" {
			detail = "-"
		}
		b.WriteString(fmt.Sprintf("| %s | %s | `%s` | `%s` | `%s` | %s |\n",
			issue.Status,
			issue.Kind,
			location,
			symbol,
			receiver,
			detail,
		))
	}
	if len(issues) > limit {
		b.WriteString(fmt.Sprintf("\n*Showing first %d of %d diagnostics.*\n", limit, len(issues)))
	}
	b.WriteString("\n")
}

func formatConfidence(confidence graph.EdgeConfidence) string {
	if confidence == graph.EdgeConfidenceHeuristic {
		return "heuristic"
	}
	return "exact"
}

func formatImpactPathMD(f analyzer.AffectedFunction) string {
	if len(f.ImpactPath) == 0 {
		return "-"
	}
	parts := make([]string, 0, len(f.ImpactPath))
	for _, step := range f.ImpactPath {
		if step.Node == nil {
			continue
		}
		parts = append(parts, "`"+step.Node.Name+"`")
	}
	if len(parts) == 0 {
		return "-"
	}
	return strings.Join(parts, " -> ")
}

func formatOwnerMD(owner string) string {
	if owner == "" {
		return "-"
	}
	return owner
}

func formatInspectHintMD(f analyzer.AffectedFunction) string {
	switch {
	case f.Confidence == graph.EdgeConfidenceHeuristic:
		return "Verify this call path manually; edge resolution was heuristic."
	case f.Depth <= 1 && f.Node != nil && f.Node.IsExport:
		return "Check API contract and direct callers first."
	case f.CallerCount >= 5:
		return "Audit high fan-in callers and downstream behavior."
	case f.Node != nil && f.Node.IsTest:
		return "Likely test-only impact; confirm no production dependency leak."
	default:
		return "Inspect implementation and covered tests along this path."
	}
}

func groupByRiskMD(funcs []analyzer.AffectedFunction) (high, medium, low []analyzer.AffectedFunction) {
	for _, f := range funcs {
		switch f.Risk {
		case analyzer.RiskHigh:
			high = append(high, f)
		case analyzer.RiskMedium:
			medium = append(medium, f)
		case analyzer.RiskLow:
			low = append(low, f)
		}
	}
	return
}

// PostGitHubComment posts or updates a blast radius comment on the current PR.
func PostGitHubComment(result *analyzer.AnalysisResult) error {
	// Check gh is available
	if _, err := exec.LookPath("gh"); err != nil {
		return fmt.Errorf("'gh' CLI not found — install from https://cli.github.com")
	}

	// Get current PR number
	prNum, err := getCurrentPR()
	if err != nil {
		return fmt.Errorf("detecting current PR: %w (are you on a PR branch?)", err)
	}

	body := FormatMarkdownComment(result)

	// Try to find and update existing comment
	existingID, err := findExistingComment(prNum)
	if err == nil && existingID != "" {
		return updateComment(existingID, body)
	}

	// Create new comment
	return createComment(prNum, body)
}

func getCurrentPR() (string, error) {
	out, err := exec.Command("gh", "pr", "view", "--json", "number", "-q", ".number").Output()
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(out)), nil
}

func findExistingComment(prNum string) (string, error) {
	out, err := exec.Command("gh", "api",
		fmt.Sprintf("repos/{owner}/{repo}/issues/%s/comments", prNum),
		"--jq", fmt.Sprintf(`.[] | select(.body | contains("%s")) | .id`, commentMarker),
	).Output()
	if err != nil {
		return "", err
	}
	id := strings.TrimSpace(string(out))
	if id == "" {
		return "", fmt.Errorf("not found")
	}
	// If multiple lines, take the first
	if idx := strings.Index(id, "\n"); idx != -1 {
		id = id[:idx]
	}
	return id, nil
}

func updateComment(commentID, body string) error {
	payload, err := json.Marshal(map[string]string{"body": body})
	if err != nil {
		return fmt.Errorf("marshaling payload: %w", err)
	}
	cmd := exec.Command("gh", "api", "-X", "PATCH",
		fmt.Sprintf("repos/{owner}/{repo}/issues/comments/%s", commentID),
		"--input", "-")
	cmd.Stdin = bytes.NewReader(payload)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("updating comment: %s", string(out))
	}
	return nil
}

func createComment(prNum, body string) error {
	cmd := exec.Command("gh", "pr", "comment", prNum, "--body", body)
	out, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("creating comment: %s", string(out))
	}
	return nil
}
